import {Oswald} from "next/font/google"
// import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'
import NavBar from "@/_components/header/header";


const oswald=Oswald({
  weight:['400','700'],
  display:'swap',
  subsets:['latin'],

})


export const metadata = {
  title: "My Next app",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <NavBar />
        <div className="container mt-3">
        {children}
        </div>
      </body>
    </html>
  );
}

// about